name: Lint GitHub Actions workflows
on:
  workflow_call:

permissions: {}

jobs:
  # Runs the actionlint GitHub Action workflow file linter.
  #
  # This helps guard against common mistakes including strong type checking for expressions (${{ }}), security checks,
  # `run:` script checking, glob syntax validation, and more.
  #
  # See https://github.com/rhysd/actionlint.
  #
  # Performs the following steps:
  # - Checks out the repository.
  # - Runs actionlint.
  actionlint:
    name: Run actionlint
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
          show-progress: ${{ runner.debug == '1' && 'true' || 'false' }}

      - name: Run actionlint
        uses: docker://rhysd/actionlint:1.7.7
        with:
          args: "-color -verbose"

  # Runs the Octoscan workflow file scanner.
  #
  # Octoscan is a static vulnerability scanner for GitHub action workflows.
  #
  # See https://github.com/synacktiv/octoscan.
  #
  # Performs the following steps:
  # - Checks out the repository.
  # - Runs Octoscan.
  # - Uploads the results to GitHub Code Scanning.
  octoscan:
    name: Octoscan
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Run octoscan
        id: octoscan
        uses: synacktiv/action-octoscan@6b1cf2343893dfb9e5f75652388bd2dc83f456b0 # v1.0.0
        with:
          filter_triggers: ''

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@76621b61decf072c1cee8dd1ce2d2a82d33c17ed # v3.29.8
        with:
          sarif_file: ${{steps.octoscan.outputs.sarif_output}}
          category: octoscan

  # Runs the Zizmor workflow file scanner.
  #
  # Zizmor is a static analysis tool for GitHub Actions that can find many common security issues.
  #
  # See https://github.com/zizmorcore/zizmor.
  #
  # Performs the following steps:
  # - Checks out the repository.
  # - Runs Zizmor.
  # - Uploads the results to GitHub Code Scanning.
  zizmor:
    name: Zizmor
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@e92bafb6253dcd438e0484186d7669ea7a8ca1cc # v6.4.3

      - name: Run zizmor
        run: uvx zizmor@1.9.0 --format sarif . > results.sarif
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@76621b61decf072c1cee8dd1ce2d2a82d33c17ed # v3.29.8
        with:
          sarif_file: results.sarif
          category: zizmor

  # Runs the Poutine workflow file scanner.
  #
  # Poutine is a security scanner that detects misconfigurations and vulnerabilities in the build pipelines of a repository.
  #
  # See https://github.com/boostsecurityio/poutine.
  #
  # Performs the following steps:
  # - Checks out the repository.
  # - Runs Poutine.
  # - Uploads the results to GitHub Code Scanning.
  poutine:
    name: Poutine
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
    timeout-minutes: 10
    steps:
    - name: Checkout repository
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        persist-credentials: false

    - name: Run Poutine
      uses: boostsecurityio/poutine-action@84c0a0d32e8d57ae12651222be1eb15351429228 # v0.15.2

    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@76621b61decf072c1cee8dd1ce2d2a82d33c17ed # v3.29.8
      with:
        sarif_file: results.sarif
        category: poutine
